# Generated by Django 4.2.2 on 2023-07-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_patterns_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patterns_employees',
            options={'verbose_name': 'Шаблон-Сотрудник', 'verbose_name_plural': 'Шаблон-Сотрудники'},
        ),
    ]
