# Generated by Django 4.2.2 on 2023-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'Причина пропуска',
                'verbose_name_plural': 'Причины пропусков',
            },
        ),
    ]
