# Generated by Django 4.2.2 on 2023-09-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0007_rename_times_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenses',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
