# Generated by Django 4.2.2 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_alter_patterns_employees_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
            options={
                'verbose_name': 'Временной промежуток',
                'verbose_name_plural': 'Временные промежутки',
            },
        ),
    ]
