# Generated by Django 4.2.2 on 2023-07-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0006_absenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Times',
            new_name='Periods',
        ),
    ]
