# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercoConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(unique=True)),
                ('port', models.CharField(unique=True)),
                ('login', models.CharField(unique=True)),
                ('password', models.CharField(unique=True)),
                ('sdk_name', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Настройки подключения',
                'verbose_name_plural': 'Настройки подключения',
            },
        ),
    ]
