# Generated by Django 4.2.2 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('host', models.CharField(unique=True)),
                ('gateway', models.CharField(unique=True)),
                ('netmask', models.CharField(unique=True)),
                ('mac', models.CharField(unique=True)),
                ('id_internal', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
