# Generated by Django 4.2.2 on 2023-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='gateway',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='netmask',
            field=models.CharField(),
        ),
    ]
