# Generated by Django 4.2.2 on 2023-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_devices_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='mac',
            field=models.CharField(),
        ),
    ]
