# Generated by Django 4.2.2 on 2023-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenteeism', models.CharField()),
                ('lateness', models.CharField()),
                ('early', models.CharField()),
                ('lateness_early', models.CharField()),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
