# Generated by Django 4.2.2 on 2023-09-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='purpose',
            field=models.CharField(default='#ffffff'),
            preserve_default=False,
        ),
    ]
